name: mp_build_tools
description: The MPFlutter build tools.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  path: any
  crypto: ^3.0.1
  cli_dialog: ^0.5.0
  win32: ">=2.0.0"
  http: ^0.13.1