name: Build and deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: |
        cd packages/mp_dom_runtime/
        npm install -g browserify uglify-js typescript terser
        npm install
        npm run build
        cd ../mp_kbone
        npm install
        npm run build
        cd ../mp_dom_runtime
        git config --global user.email "ci@mpflutter.com"
        git config --global user.name "GitHub CI bot"
        git clone https://github.com/mpflutter/dist.git mpflutter_dist
        mkdir -p mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")
        cp -rf dist_web mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")/dist_web
        cp -rf dist_swan mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")/dist_swan
        cp -rf dist_weapp mpflutter_dist/$(echo ${{ github.ref }} | sed -e "s/refs\/tags\///")/dist_weapp
        cd mpflutter_dist
        git add .
        git diff-index --quiet HEAD || git commit --message "CI Bot commit"
        git push "https://ponycui:${{ secrets.GH_TOKEN }}@github.com/mpflutter/dist.git" --set-upstream "master"
 